apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: spring-petclinic-aks
  name: spring-petclinic-aks
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: spring-petclinic-aks
  sessionAffinity: None
  type: LoadBalancer